USE [SQLTest]
GO

/****** Object:  Table [dbo].[Heading]    Script Date: 06/08/2021 14:28:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Heading](
	[JobKeyID] [int] NOT NULL,
	[DateInProduction] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[JobKeyID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

